### ISSUE TITLE
get sum of RMS

### ISSUE THREAD

**Issue by mhamilt** [sophieyeeyan/screamTrial#2]
Need to get the sum of RMS values in

https://github.com/sophieyeeyan/screamTrial/blob/ec29e57f19c8e287301855f636f53c0b044b81a5/trial/GameViewController.swift#L101-L116

**Comment by mhamilt** [comment]
First of all, I'd change the names o

- `someVariable`
- `aVariable`
- `aVariablesum`

As they don't really tell you huge amount about what they are meant to represent.

Secondly `someVariable` is just a single number

https://github.com/sophieyeeyan/screamTrial/blob/b76ee0b96a2ef5df4418b560e18b84e98fd38536/trial/AppDelegate.swift#L16

which means `aVariable` is a single number

https://github.com/sophieyeeyan/screamTrial/blob/ec29e57f19c8e287301855f636f53c0b044b81a5/trial/GameViewController.swift#L102

which means there really isn't anything _to_ sum at this point. I think you may want to think about what `loudControl` does and what `appDelegate.someVariable` represents.

`someVariable` (again, bad name, change it) should just be the current RMS value

https://github.com/sophieyeeyan/screamTrial/blob/b76ee0b96a2ef5df4418b560e18b84e98fd38536/trial/AppDelegate.swift#L68

so all you should need to do is

```swift
@objc func loudControl()
{
  let currentRms = appDelegate.someVariable
  
  if currentRms > 0.05 
  {
    print("this is loud mate")
    animation1.startAnimating()
    animation2.startAnimating()  
  } 
  else 
  {
    print("this is quiet mate")
  }
}
```

wether or not the animation works correctly is a separate problem entirely

**Comment by sophieyeeyan** [comment]
you mentioned current RMS value is a single number `Line 16 in b76ee0b`
when I print out the value, the console will show the value every second
So that why I was trying to create a sum of it

Did I mix up something here  ? 

> var someVariable: Float = 0.0

**Comment by sophieyeeyan** [comment]
you mentioned current RMS value is a single number [Line 16 in b76ee0b](url)
when I print out the value, the console will show the value every second
So that why I was trying to create a sum of it

**Comment by mhamilt** [comment]
RMS is already an average so summing it seems a little redundant.

when you say _sum_ do you mean _average_

**Comment by sophieyeeyan** [comment]
for sum, I mean adding the rms value since the app started

**Comment by mhamilt** [comment]
If that is the case, your sum will just keep getting infinitely bigger, you will have to have some kind of way to make it smaller.

What might make more sense is _what do you want to do with your sum?_

**Comment by sophieyeeyan** [comment]
I am doing two things with my sum:
1. Play the animation when the sum reaches a threshold
2. Link the sum with a Progress bar

**Comment by mhamilt** [comment]
I don't think that is going to be the most robust way to go about it.

What you ideally want to do is

- [ ] get the RMS of incoming of microphone
- [ ] test RMS
    - [ ] is RMS greater than threshold 
    - [x] has RMS been greater than threshold for _N_ seconds
- [ ] create a progress bar
     - [ ] that just goes up with time (nothing to do with RMS)
     - [ ] that goes up the longer RMS has been above the threshold
 - [ ] play animation
     - [ ] play animation regardless of anything else
     - [ ] play animation after _N_ seconds
     - [ ] play animation if RMS has  been greater than threshold for _N_ seconds

tackle each one of these in turn.

The problem with just summing RMS values is that it will only get bigger. A sum will always go above the threshold regardless of the value, eventually. If you approach things that way you will have less control.

**Comment by sophieyeeyan** [comment]
okay I got your point now 
any tips on how to achieve this task as I was trying to resolve it through sum 
-  RMS been greater than threshold for N seconds

**Comment by mhamilt** [comment]
for _RMS been greater than threshold for N seconds_ here is a rough set of problems to solve

- [x] create a timer that triggers every second called `checkLoudness`
- [x] time how long the application has been running
- [x] display this time on the screen
- [x] start the animation after the timer has passed `3` seconds (you can change `3` to a variable later
- [x] test if RMS is greater than a number
- [x] create a `bool` that is `true` if RMS is greater than a number
- [x] create a variable called `timeAboveThreshold`
- with `checkLoudness`
    - [x] add `1` to  `timeAboveThreshold` if RMS is greater than threshold
    - [x] else `timeAboveThreshold = 0`
    - [x] if  `timeAboveThreshold` is greater than `3` display a message on screen
