### ISSUE TITLE
Controlling Sprite

### ISSUE THREAD

**Issue by sophieyeeyan** [sophieyeeyan/screamTrial#3]
Hello. I have another question. @mhamilt 
I have two sprites. 

> https://github.com/sophieyeeyan/screamTrial/blob/15cff860ca37bece5dc1a854d082b487cbf54214/trial/GameViewController.swift#L102

And I want to display the second sprite: roar_2 when the currentRms is bigger than a certain level. And when currentRms is lower than a certain level, it will go back to the first sprite: roar_1. 
currently, I am using the following line to animate the sprites, which the animation will be looping.
> https://github.com/sophieyeeyan/screamTrial/blob/15cff860ca37bece5dc1a854d082b487cbf54214/trial/GameViewController.swift#L87

Can you advise me which function I should use to achieve the effect I want? Thank you in advance.

**Comment by mhamilt** [comment]
can you get:

- [ ] `"roar_1"`  to display by itself?
- [ ] `"roar_2"` to display by itself?
- [ ] hard code which sprite shows? e.g.
```swift
let showRoar1 = true;
if (showRoar1)
{
  animation1.startAnimating() 
}
else
{
  animation2.startAnimating() 
}
```

**Comment by sophieyeeyan** [comment]
Hello. I am not so sure what you mean by display the sprite by itself.
I add the image through the main storyboard and make an outlet that connects animation2 with the sprites. So yes I can display roar_1 by itself. 

> https://github.com/sophieyeeyan/screamTrial/blob/15cff860ca37bece5dc1a854d082b487cbf54214/trial/GameViewController.swift#L19

I do not know how to display roar_2 by itself through code. 
p.s. animation1 is another UIimage view

**Comment by mhamilt** [comment]
I see, so you don't want to animate the image at all, you just want to change which image is shown. 
If that is the case, you just need to create two `UIImage` objects, one for each image. 

e.g.

```swift

class GameViewController: UIViewController {
    
    var roar1 : UIImage!;
    var roar2 : UIImage!;
    // blah blah
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // blah blah
        let dinoImages = ["roar_1", "roar_2"]
        roar1 = UIImage(named: dinoImages[0])!
        roar2 = UIImage(named: dinoImages[1])!
        // blah blah
    }
    
    @objc func checkLoudness()
    {
        let showRoar1 = true;
        if (showRoar1)
        {
            animation2.image = roar1
        }
        else
        {
            animation2.image = roar2
        }
    }
}
```

**Comment by sophieyeeyan** [comment]
Can I ask what does the following code is doing? The computer shows two warnings when I run it. 

if (showRoar1)
        {
            animation2.image = roar1.   Condition always evaluates to true
        }
        else
        {
            animation2.image = roar2      Will never be executed
        }

**Comment by mhamilt** [comment]
This is really just pseudo-swift code

```swift
        let showRoar1 = true;
        if (showRoar1)
        {
            animation2.image = roar1
        }
        else
        {
            animation2.image = roar2
        }
```

What I'm suggesting is that you need to display one of two images. Before you try and display an image programmatically you should see if you can simply switch between images by changing the actual code.


Another set of problems to solve are

- [x] show only `roar_1`
- [x] show only `roar_2`
- [x] show either `roar_1` or `roar_2` based on a boolean (the above code)
- [x] show either `roar_1` or `roar_2` based on time above rms threshold

**Comment by mhamilt** [comment]
@sophieyeeyan  what is the latest on this?

**Comment by sophieyeeyan** [comment]
Hello thanks for asking. I am able to fix this issue now. 
I thought something wrong with my sprite control code and my sprite won't change in response to the loudness.
It turns out my code in loudness control is incorrect, as I mixed up the concepts of Int / Float / Double.
